name: Flutter Chat Workshop

type: flutter

steps:
  - name: Introduction
    directory: 01_introduction
    has_solution: false
  - name: Initialize App
    directory: 02_initialize_app
    has_solution: true
  - name: Setup Layout
    directory: 03_setup_layout
    has_solution: true
  - name: Chat List
    directory: 04_chat_list
    has_solution: true
  - name: Write Message
    directory: 05_write_message
    has_solution: true
  - name: Store Read Messages
    directory: 06_read_messages
    has_solution: true
  - name: Send Message
    directory: 07_send_message
    has_solution: true
