name: flutter_chat_workshop

environment:
  sdk: "^3.1.2"

# https://dartpad.dev/workshops.html?webserver=
# https://raw.githubusercontent.com/fluttermtl/flutter_chat_workshop/main

dependencies:
  cloud_firestore:
  firebase_core:
  flutter:
    sdk: flutter
  intl:
